name: games-notifier

on:
    schedule:
        - cron: "0 * * * *"
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo content
              uses: actions/checkout@v2

            - name: setup python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.9"

            - name: install python packages
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install playwright flare-bypasser

            - name: install system dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y xvfb

            - name: install browser
              run: python -m playwright install chromium
                
            - name: start flare-bypass server
              run: |
                python -m flare_bypasser.server > server.log 2>&1 &
                echo "Waiting for server to start..."
                sleep 10
                # Check if server is running
                if curl -s http://localhost:8080/v1 -o /dev/null; then
                  echo "Server is running"
                else
                  echo "Server failed to start. Server logs:"
                  cat server.log
                  exit 1
                fi
              
            - name: execute py script
              env:
                GIST_ID: ${{ secrets.GIST_ID }}
                GH_TOKEN: ${{ secrets.GH_TOKEN }}
                WEBHOOKS_PATH: ${{ secrets.WEBHOOKS_PATH }}
                PERP_TOKEN: ${{ secrets.PERP_TOKEN }}
                PERP_MODEL: ${{ vars.PERP_MODEL }}
                PERP_PROMPT: ${{ vars.PERP_PROMPT }}
              run: python main.py
