name: Run Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        GIST_ID: ${{ secrets.GIST_ID }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        WEBHOOKS_PATH: ${{ secrets.WEBHOOKS_PATH }}
        PERP_TOKEN: ${{ secrets.PERP_TOKEN }}
        PERP_MODEL: ${{ secrets.PERP_MODEL }}
        PERP_PROMPT: ${{ vars.PERP_PROMPT }}
      run: python -m unittest discover -s . -p "test_*.py"